import type { LiveFeedPost } from "@/components/live/types";

export const liveFeedPosts: LiveFeedPost[] = [
  {
    id: "post-1",
    username: "@mira.nights",
    avatarUrl: "https://images.unsplash.com/photo-1546961329-78bef0414d7c?auto=format&fit=crop&w=200&q=80",
    venue: "Neon Harbor",
    location: "Downtown Newark",
    postedAt: "5 min ago",
    mediaUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
    mediaType: "image",
    caption: "DJ set just flipped the room. Lights are unreal and the crowd keeps growing.",
    vibeScore: 9,
    hearted: true,
    commentsCount: 12,
    venueAverageVibe: 8.7,
  },
  {
    id: "post-2",
    username: "@cityafterdark",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
    venue: "Velvet Room",
    location: "Ironbound",
    postedAt: "11 min ago",
    mediaUrl: "https://cdn.coverr.co/videos/coverr-friends-at-a-nightclub-1579/1080p.mp4",
    mediaType: "video",
    caption: "Cocktail line is short right now. Perfect timing before the headline set at midnight.",
    vibeScore: 7,
    commentsCount: 6,
    venueAverageVibe: 7.9,
  },
  {
    id: "post-3",
    username: "@alexgoesout",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    venue: "Skyline Loft",
    location: "University Heights",
    postedAt: "22 min ago",
    mediaUrl: "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=1200&q=80",
    mediaType: "image",
    caption: "Rooftop is chill but active. Great for groups that want music without chaos.",
    vibeScore: 6,
    commentsCount: 4,
    venueAverageVibe: 6.4,
  },
  {
    id: "post-4",
    username: "@danybeats",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
    venue: "Neon Harbor",
    location: "Downtown Newark",
    postedAt: "34 min ago",
    mediaUrl: "https://images.unsplash.com/photo-1571266028243-d220c9d6b084?auto=format&fit=crop&w=1200&q=80",
    mediaType: "image",
    caption: "Second floor dance room is way more lit than the main stage right now.",
    vibeScore: 8,
    commentsCount: 9,
    venueAverageVibe: 8.7,
  },
];

export const availableVenues = [
  "Neon Harbor",
  "Velvet Room",
  "Skyline Loft",
  "Midnight Alley",
  "Pulse Social Club",
  "Afterglow Lounge",
];
